import React from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import Footer from "../footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Third Frame",
  description: "Generated by create next app",
};
import "./thirdframe.css";
import Ship from "./ship.jpg";
import Location from "./location.jpg";
import Calender from "./calendar.jpg";
import Edit from "./edit2.jpg";
import Vector from "./Vector.jpg";
import Arrow from './arrowdown2.jpg';

export default function page() {
  return (
    <div className="thirdFrame">
      <div className="thirdFrame-nav">
        <h1>
          Ship<span>mate</span>
        </h1>
        <div className="thirdFrame-nav-div">
          <div>
            <Image src={Vector} alt="vector"></Image>
          </div>
          <button>Track shipment</button>
        </div>
      </div>

      <div className="load-div">
        <Image src={Ship} alt="ship" />
        <p>Load</p>
      </div>

      <div className="round-div">
        <div className="round-div-div">
          <div>1</div>
          <p>Search</p>
        </div>
        <div className="sidebar"></div>
        <div className="round-div-div">
          <div>2</div>
          <p>Recommended services</p>
        </div>
        <div className="sidebar"></div>
        <div className="round-div-div">
          <div>3</div>
          <p>Results</p>
        </div>
        <div className="sidebar"></div>
        <div className="round-div-div booking">
          <div></div>
          <p>Booking</p>
        </div>
      </div>

      <div className="middle-content">
        <div className="middle-inner-div">
          <div className="big-div">
            <Image src={Location} alt="location"></Image>
            <p>Delhi, 110003</p>
          </div>
          <div className="big-div">
            <Image src={Location} alt="location"></Image>
            <p>Shanghai 200080</p>
          </div>
          <div className="big-div">
            <Image src={Calender} alt="calender"></Image>
            <p>13 April 2023</p>
          </div>
          <div className="small-div">
            <Image src={Ship} alt="ship" />
            <p>114.21KG - AIR</p>
          </div>
        </div>
        <div className="sideline"></div>
        <Image src={Edit} alt="edit" className="edit"></Image>
      </div>

      <div className="linebar"></div>

      <div className="best-value-div">
         <div className="best-value-div-div">
          <p>Best Value 5-5 days. $3,121</p>
         </div>
         <p>Quickest 5-5 days. $3,121</p>
         <p>Cheapest 5-5 days. $3,121</p>
      </div>
      <p className="best">3 Top Quote <span>(6 in Total)</span></p>
      <div className="list">
         <div className="filters">
          <p>Filters</p>
          <Image src={Arrow} alt="arrow"></Image>
         </div>
         <div className="price">
          <p>Price</p>
          <Image src={Arrow} alt="arrow"></Image>
          </div>
         <div className="modes">
          <p>Modes</p>
         <Image src={Arrow} alt="arrow"></Image>
         </div>
         <div className="seller">
          <p>Seller</p>
         <Image src={Arrow} alt="arrow"></Image>
         </div>
      </div>
    </div>
  );
}
