import React from 'react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Contact us',
  description: 'Generated by create next app',
}

export default function page() {
  return (
    <div>Contact us</div>
  )
}
