import React from 'react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'About us',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <div>About</div>
  )
}
