import React from 'react'
import { Inter } from 'next/font/google'
import './frame1.css';
 import Footer from '../footer';

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
    title: 'First Frame',
    description: 'Generated by create next app',
}
export default function page() {
    return (
        <div className='first-frame-container'>
            <nav className='first-frame-nav'>
                <h1>Ship<span>mate</span></h1>
                <div className='first-frame-nav-div'>
                    <button className='first-frame-button1'>Login</button>
                    <button className='first-frame-button2'>Learn more</button>
                </div>
            </nav>
            <div className='first-frame-div1'>
                <h1 className='first-frame-h1'>Hassle-Free Shipping Solution</h1>
                <p className='first-frame-p'>Compare book and manage your freight accross the world top logistics providers, all on one platform.</p>
            </div>
            <div className='first-frame-div2'>
                <ul className='first-frame-div-ul'>
                    <li><i class="fa-solid fa-location-dot"></i> Origin, Port, City</li>
                    <li><i class="fa-solid fa-location-dot"></i> Destination, Port, City</li>
                    <div className='first-frame-div-ul-border border1'></div>
                    <li><i class="fa-solid fa-calendar-days"></i>13 April 2023</li>
                    <div className='first-frame-div-ul-border border2'></div>
                    <li><i class="fa-solid fa-ship"></i>Load</li>
                    <div className='first-frame-div-ul-border border3'></div>
                    <button><i class="fa-solid fa-arrow-right"></i></button>
                </ul>
            </div>
            <div className='first-frame-div3'>
                <h5>Services</h5>
                <div className='first-frame-div3-div'>
                    <div className='first-frame-div3-div-div'>
                        {/* <div className='services'><i class="fa-solid fa-ship"></i><p>Freight Services</p></div> */}
                        <p className='services'><i class="fa-solid fa-ship" style={{ color: '#0075FF' }}></i> Freight Services</p>
                        <div className='first-frame-div3-border'></div>
                        <p className='first-frame-div3-div-p'>Open new Oppertunities to grow your business. Enter new markets and discovery new continents. We are with you, door-to-door.</p>
                    </div>
                    <div className='first-frame-div3-div-div'>
                        {/* <div className='services'><i class="fa-solid fa-briefcase"></i><p>Business Services</p></div> */}
                        <p className='services'><i class="fa-solid fa-briefcase" style={{ color: '#FF4747' }}></i>Business Services</p>
                        <div className='first-frame-div3-border'></div>
                        <p className='first-frame-div3-div-p'>We support your goals for growth with cargo insurance, online payments and paperless workflow. Take your business to the next level.</p>
                    </div>
                    <div className='first-frame-div3-div-div'>
                        {/* <div className='services'><i class="fa-solid fa-globe"></i><p>Shipping & Logistics</p></div> */}
                        <p className='services'><i class="fa-solid fa-globe" style={{ color: '#FF6813' }}></i>Shipping & Logistics</p>
                        <div className='first-frame-div3-border'></div>
                        <p className='first-frame-div3-div-p'>Find powerfull solutions to meet your diverse transportation needs. Agile solution to handle all your supply chain needs.</p>
                    </div>
                    <div className='first-frame-div3-div-div'>
                        {/* <div className='services'><i class="fa-regular fa-message"></i><p>24/7 Support</p></div>
                        <div className='first-frame-div3-border'></div> */}
                        <p className='services'><i class="fa-regular fa-message" style={{ color: '#47A7FF' }}></i>24/7 Support</p>
                        <div className='first-frame-div3-border'></div>
                        <p className='first-frame-div3-div-p'>Receive support from our experts all over the world at every stage of the process, 24/7.</p>
                    </div>
                </div>
            </div>
            <div className='message'>
                <button><i class="fa-solid fa-message fa-flip-horizontal"></i></button>
            </div>
            <div className='first-frame-wave'>
                <Footer />
            </div>
        </div>
    )
}
